void execDeviceCommand(int command);
void showDeviceMenu();
int inputDeviceMenu();
void signup();
void in();
void hanging();
void show();
void chat();
void pendentMessage();
void showOnlineUsers();
void out();